[0.009s] Invoking command in '/home/chayakorn/ros_ws/build/rc_pwm_pkg': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/chayakorn/ros_ws/install/control_pkg:/opt/ros/humble /usr/bin/cmake --build /home/chayakorn/ros_ws/build/rc_pwm_pkg -- -j16 -l16
[0.037s] -- Found ament_cmake: 1.3.11 (/opt/ros/humble/share/ament_cmake/cmake)
[0.145s] -- Found ament_lint_auto: 0.12.11 (/opt/ros/humble/share/ament_lint_auto/cmake)
[0.195s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.197s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.200s] -- Found rosidl_adapter: 3.1.6 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.227s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.386s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.386s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.386s]   rc_pwm_pkg --arguments-file
[0.386s]   /home/chayakorn/ros_ws/build/rc_pwm_pkg/rosidl_adapter__arguments__rc_pwm_pkg.json
[0.386s]   --output-dir
[0.386s]   /home/chayakorn/ros_ws/build/rc_pwm_pkg/rosidl_adapter/rc_pwm_pkg
[0.386s]   --output-file
[0.386s]   /home/chayakorn/ros_ws/build/rc_pwm_pkg/rosidl_adapter/rc_pwm_pkg.idls)
[0.387s]   returned error code 1:
[0.387s] 
[0.387s]   Traceback (most recent call last):
[0.387s] 
[0.387s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.387s]       return _run_code(code, main_globals, None,
[0.387s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.387s]       exec(code, run_globals)
[0.387s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.387s]       sys.exit(main())
[0.387s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.387s]       abs_idl_file = convert_to_idl(
[0.387s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.387s]       return convert_msg_to_idl(
[0.387s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.387s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.387s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[0.387s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[0.387s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[0.387s]       self.base_type = BaseType(
[0.388s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.388s]       raise InvalidResourceName(
[0.388s] 
[0.388s]   rosidl_adapter.parser.InvalidResourceName: 'Pub_pwm' is an invalid message
[0.388s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.388s] 
[0.388s] Call Stack (most recent call first):
[0.388s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.388s]   CMakeLists.txt:28 (rosidl_generate_interfaces)
[0.388s] 
[0.388s] [0m
[0.388s] -- Configuring incomplete, errors occurred!
[0.388s] See also "/home/chayakorn/ros_ws/build/rc_pwm_pkg/CMakeFiles/CMakeOutput.log".
[0.398s] gmake: *** [Makefile:747: cmake_check_build_system] Error 1
[0.401s] Invoked command in '/home/chayakorn/ros_ws/build/rc_pwm_pkg' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/chayakorn/ros_ws/install/control_pkg:/opt/ros/humble /usr/bin/cmake --build /home/chayakorn/ros_ws/build/rc_pwm_pkg -- -j16 -l16
